name: FCL-DISCOVERY Continuous Integration

on:
  pull_request:
    branches: [master, v2]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm test
      - run: npm run build
